
# Introduction

## Segmentation

## Yeast Data

chemostat oscillations: transcriptome oscillates, stable over various 
conditions, also seen in batch, and single cells from un-synchronized
chemostat and in microfluidics

here, RNA-seq over three cycles of the short period IFO strain, thus 
at unprecedented temporal resolution; unexpected singularity
during third cycle

# Methods
## Problem & Algorithm: `Karl`



## Implementation: `segmenTier`

die offiziellen zwei "demos" des R pakets sind nun fokusiert auf die
parameter, die man auch im paper kurz besprechen sollte. eine simulierte
clusteringsequenz erklaert die 3 verwendeten scoring functionen (dzt. 
"ccls", "ccor" und "icor"),  und zeigt an denen auch die im weiteren
nicht mehr relevanten interne algo-details (variationen in  S(i,c) berechnung 
und back-tracing); 

die zweite demo wie bisher eine kurze domain um SRG1, um die relevanten 
parameter fuer echte daten zu illustrieren.
das sind
1) trafo der rohdaten: dft als snr + dc scaling
2) nui-cluster korrelationen (zb. -3.. +3 statt -1..+1)
3) exponent auf den korrelationsmatrizen 
4) zufallskomponente in der k-means initialisierung

ohne (1) gibt es klare ueberfragmentierung,
va. 2 hilft die enden tighter zu machen, naeher an total;
va. (2) und (3) haben sonst aehnliche effekte, man kann mit
ihnen interne bruchstellen (FP in guten transkripten, FN 
zw. sehr engen benachbarten in-phase transkripten) fine-tunen,
is aber sehr schwierig freihaendig zu optimieren.

als outlook sind segmenTier (u. segmenTools) so gebaut, dass man (a)
auto- und systematisch optimierungsstrategien fuer obige parameter und 
v.a. das fine-tuning implementieren kann, und (b) die zufallskomponente in (4)
nutzen kann fuer systematische consensus definition; und (c) man mit
weiterer co-variation von (2), (3) und parameter M zb. auch sequencing
artefakte, splice-sites, finden koennte; und (d) alle (1-3) angepasst
werden koennen fuer andere daten.

* `segmenTier`
** Algorithm: R & Rcpp
** Parameter scanning framework
** Plot functions 

* `segmenTools`, library & command-line scripts
** presegment.R: 
   pre-segmentation by distance cutoffs
** runSegmentier.R: 
   command-line wrapper; used for parallelization on SGE cluster
** coor2index maps to yeast R64-1-1 genome; taken from `genomeBrowser`
** parameter scan analysis framework:
   criteria: jaccard, query/target length vs. test set (ORF transcripts); 
   segment length distribution, segment phase and amplitude


## Pre-segmentation

## Parameter Scan

* Segment length distributions
* ORF Recovery: coding vs. non-coding, red vs. blue genes
** Time-series pre-processing: ash trafo of DC 
** Exponent `E` and nuissance cluster correlation `nui`

* Examples: 
** SRG1/SER3, unknown at GDH3!
* domain_046_69kb: good sense:antisense osci at cluster A gene ECM32 (DNA dependent ATPase/DNA helicase!), surrounded by D and B oscillators
** SPO7/FUN4 (primsegv3 00016) & APD1/SPP381 (primsegv3 00100)
   -> difficult separation of close in-phase transcripts,

## Segment Dynamics

* coding vs. non-coding: 
