# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myPearson <- function(x, y) {
    .Call('segmenTier_myPearson', PACKAGE = 'segmenTier', x, y)
}

#'@export
clusterCor_c <- function(data, clusters) {
    .Call('segmenTier_clusterCor_c', PACKAGE = 'segmenTier', data, clusters)
}

#'@export
clusterMaxCor_c <- function(data, clusters, mincor = 0.0, warn = 0L) {
    .Call('segmenTier_clusterMaxCor_c', PACKAGE = 'segmenTier', data, clusters, mincor, warn)
}

#' @export
scoreicor_c <- function(k, i, c, seq, M, csim) {
    .Call('segmenTier_scoreicor_c', PACKAGE = 'segmenTier', k, i, c, seq, M, csim)
}

#' @export
scorecor_c <- function(k, i, c, seq, M, csim) {
    .Call('segmenTier_scorecor_c', PACKAGE = 'segmenTier', k, i, c, seq, M, csim)
}

#' @export
scorecls_c <- function(k, i, c, seq, M, a) {
    .Call('segmenTier_scorecls_c', PACKAGE = 'segmenTier', k, i, c, seq, M, a)
}

#' @export
ccSMicor <- function(seq, c, M, Mn, csim) {
    .Call('segmenTier_ccSMicor', PACKAGE = 'segmenTier', seq, c, M, Mn, csim)
}

#' @export
ccSMccor <- function(seq, c, M, Mn, csim) {
    .Call('segmenTier_ccSMccor', PACKAGE = 'segmenTier', seq, c, M, Mn, csim)
}

#' @export
ccSMxcor <- function(seq, c, M, Mn, csim) {
    .Call('segmenTier_ccSMxcor', PACKAGE = 'segmenTier', seq, c, M, Mn, csim)
}

#' @export
ccSMncor <- function(seq, c, M, csim) {
    .Call('segmenTier_ccSMncor', PACKAGE = 'segmenTier', seq, c, M, csim)
}

#' @export
ccSMcls <- function(seq, c, M, Mn, csim) {
    .Call('segmenTier_ccSMcls', PACKAGE = 'segmenTier', seq, c, M, Mn, csim)
}

#' @export
calculateTotalScore <- function(seq, C, SM, multi = "max", verb = 1L) {
    .Call('segmenTier_calculateTotalScore', PACKAGE = 'segmenTier', seq, C, SM, multi, verb)
}

